# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us 983708408@qq.com
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring:
  application.name: phoenix-table-fixtools
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: ${TOOL_DB_URI:jdbc:phoenix:localhost:2181}
    initial-size: 5
    min-idle: 5
    max-idle: 50
    max-active: 10
    max-wait: 10000
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 600000
    validation-query: SELECT 1
    default-auto-commit: true

logging:
  file: /var/log/${spring.application.name}/${spring.application.name}_${spring.profiles.active}.log
  policy:
    maxFileSize: 1GB
    minIndex: 1
    maxIndex: 30
  root: INFO
  level:
    org:
      springframework.jdbc.core: DEBUG
      apache: INFO

repair:
  #metaCsvFile: ~/.phoenix-fixtool/meta.csv
  tableNamespace: safeclound
  tableName: tb_ammeter
  rowKeyFormat: "{csv:addrIP:},ELE_P,{csv:templateMark:},{csv:addrIPOrder:%02d},{date:yyyyMMddHHmmss}"
  maxLimit: 14400
  #startDate: DateUtils2.formatDate(DateUtils2.addDays(new Date(), -2), "yyyyMMddHHmmss")
  #endDate: DateUtils2.formatDate(DateUtils2.addDays(new Date(), -1), "yyyyMMddHHmmss")
  randomMinOffsetPercentage: 0.8976
  randomMaxOffsetPercentage: 1.1024
  threadPools: 1
  